version: '3'

services: 
  questify-conversation-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: questify-conversation-service
    ports: 
      - "${PORT}:${PORT}"
    volumes:
      - node_modules:/usr/app/node_modules
      - ./app:/usr/app
    env_file:
      - .env
    restart: always
    networks:
      - questify-network

  questify-conversation-service-mongodb:
    image: mongo:latest 
    container_name: questify-conversation-service-mongodb
    ports:
      - "${MONGO_PORT}:27017" 
    env_file:
      - .env
    restart: always
    networks:
      - questify-network
      
volumes:
  node_modules:

networks:
  questify-network:
    external: true